import { auth, db, firebasePaths, getCurrentUserDataRootKey } from "../../shared/firebase/index.js";
import { ref, onValue, set, remove } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-database.js";
import { createLeafletMap, DEFAULT_MAP_CENTER_SPAIN, destroyLeafletMap, ensureLeaflet, invalidateLeafletMap } from "../../shared/vendors/leaflet.js";
import { trackedOnValue } from "../../shared/firebase/read-debug.js";
import { getCountryEnglishName } from "./countries.js";

const $id = (id) => document.getElementById(id);
const WORLD_PATH = (uid) => firebasePaths.world(uid);
const id = () => `${Date.now()}_${Math.random().toString(16).slice(2)}`;
const stars10 = (v = 0) => "★".repeat(Math.round(v)).padEnd(10, "☆");
const hav = (a, b, c, d) => { const R = 6371000; const to = (x) => x * Math.PI / 180; const d1 = to(c - a), d2 = to(d - b); const q = Math.sin(d1 / 2) ** 2 + Math.cos(to(a)) * Math.cos(to(c)) * Math.sin(d2 / 2) ** 2; return 2 * R * Math.atan2(Math.sqrt(q), Math.sqrt(1 - q)); };

const state = { initialized:false, unsub:null, rootRef:null, map:null, miniMap:null, miniMarkers:[], markers:new Map(), geography:[], places:[], userCenter:{ lat:DEFAULT_MAP_CENTER_SPAIN[0], lon:DEFAULT_MAP_CENTER_SPAIN[1] }, selectedGeo:null, selectedPlace:null, geoResults:[], placeResults:[], rating:0, activeWindow:"map", addMode:"geo", highlightedPlaceId:"", toastTimer:null };

const normalize = (r = {}, kind = "geography") => ({ id:r.id || id(), kind, name:String(r.name || r.placeName || "").trim(), label:String(r.label || r.displayName || r.name || "").trim(), country:String(r.country || "").trim(), countryCode:String(r.countryCode || r.country_code || "").trim().toUpperCase(), city:String(r.city || "").trim(), region:String(r.region || r.subdivision || "").trim(), postalCode:String(r.postalCode || "").trim(), category:String(r.category || r.type || "").trim(), emoji:String(r.emoji || (kind === "places" ? "🏪" : "📍")).trim(), note:String(r.note || "").trim(), rating:Number.isFinite(Number(r.rating)) ? Number(r.rating) : null, lat:Number(r.lat), lon:Number(r.lon), createdAt:Number(r.createdAt || Date.now()), updatedAt:Date.now() });
const normalizeLocationAddress = (result = {}) => { const a = result?.address || {}; return { label:String(result?.display_name || result?.label || "").trim(), name:String(result?.name || result?.display_name || "").split(",")[0].trim(), country:String(a.country || "").trim(), countryCode:String(a.country_code || "").trim().toUpperCase(), region:String(a.state || a.region || "").trim(), city:String(a.city || a.town || a.village || a.municipality || "").trim(), municipality:String(a.municipality || "").trim(), postalCode:String(a.postcode || "").trim(), lat:Number(result?.lat), lon:Number(result?.lon ?? result?.lng), address:a }; };
const flag = (cc = "") => { const s = String(cc || "").trim().toUpperCase(); return /^[A-Z]{2}$/.test(s) ? String.fromCodePoint(...[...s].map((c) => 127397 + c.charCodeAt(0))) : "🌍"; };
const normalizeCountryFromAddress = (address = {}) => ({ countryCode:String(address?.country_code || "").trim().toUpperCase(), country:String(address?.country || "").trim() });

function showToast(text = "Lugar guardado") { const el = $id("world-feedback"); if (!el) return; el.textContent = text; el.classList.add("show"); clearTimeout(state.toastTimer); state.toastTimer = setTimeout(() => el.classList.remove("show"), 1700); }
function closeAddModal(){ $id("world-add-toggle").checked = false; }
function resetWorldAddModalState(){ state.selectedGeo = null; state.selectedPlace = null; state.geoResults = []; state.placeResults = []; state.rating = 0; ["world-geo-q","world-geo-note","world-place-q","world-place-note"].forEach((k)=>{ const el=$id(k); if (el) el.value=""; }); $id("world-place-radius").value = "1000"; $id("world-geo-results").innerHTML = ""; $id("world-place-results").innerHTML = ""; renderRating(); renderPlaceResults(); }

function renderWorldGeoMode(){ $id("world-geo-mode").hidden = false; $id("world-place-mode").hidden = true; }
function renderWorldPlaceMode(){ $id("world-place-mode").hidden = false; $id("world-geo-mode").hidden = true; initMiniMap(); }
function setAddMode(mode){ state.addMode = mode; $id("world-add-mode-geo").classList.toggle("active", mode === "geo"); $id("world-add-mode-place").classList.toggle("active", mode === "place"); if (mode === "geo") renderWorldGeoMode(); else renderWorldPlaceMode(); }

function ratingFromPointer(el, clientX){ const rect = el.getBoundingClientRect(); return Math.max(0, Math.min(10, ((clientX - rect.left) / Math.max(rect.width, 1)) * 10)); }
function renderRating(){ const el = $id("world-rating-stars"); if(!el) return; const value = state.rating; el.setAttribute("aria-valuenow", String(value.toFixed(1))); el.innerHTML = `<div class="world-rating-track"><div class="world-rating-fill" style="width:${(value/10)*100}%"></div><div class="world-rating-text">${stars10(value)} ${value.toFixed(1)}/10</div></div>`; }

function renderGeoResults(){ const root = $id("world-geo-results"); root.innerHTML = state.geoResults.map((r, i) => { const active = state.selectedGeo?.id === `geo_${i}`; return `<button class="world-result-card ${active ? "is-selected" : state.selectedGeo ? "is-dimmed" : ""}" data-geo-pick="${i}"><strong>${r.label || r.name}</strong><small>${r.label || ""}</small></button>`; }).join(""); }
function renderPlaceResults(){ const root = $id("world-place-results"); root.innerHTML = state.placeResults.map((r, i) => { const active = state.selectedPlace?.id === `place_${i}`; return `<button class="world-result-card ${active ? "is-selected" : state.selectedPlace ? "is-dimmed" : ""}" data-place-pick="${i}" data-place-center="${i}"><strong>${r.name}</strong><small>${r.city || ""} · ${Math.round(r.distance)}m</small></button>`; }).join(""); renderMiniMapMarkers(); }

function renderMiniMapMarkers(){ if (!state.miniMap || !window.L) return; state.miniMarkers.forEach((m)=>m.remove()); state.miniMarkers = []; const L = window.L; state.placeResults.forEach((r, i) => { if (!Number.isFinite(r.lat) || !Number.isFinite(r.lon)) return; const selected = state.selectedPlace?.id === `place_${i}`; const marker = L.circleMarker([r.lat, r.lon], { radius:selected ? 10 : 7, fillOpacity:selected ? 1 : 0.82, color:selected ? "#ffe6ac" : "#fff", fillColor:selected ? "#ff9640" : "#5ec7ff", weight:2 }).addTo(state.miniMap); marker.on("click", ()=>{ pickPlace(i); state.miniMap.setView([r.lat, r.lon], 17); marker.bindPopup(`<b>${r.name}</b><br>${r.city || ""}`).openPopup(); }); state.miniMarkers.push(marker); }); }

function renderMap(){ if(!window.L) return; const host = $id("world-map"); if(!host) return; if(!state.map) state.map = createLeafletMap(host, { center:[state.userCenter.lat, state.userCenter.lon], zoom:13 }); state.markers.forEach((m)=>m.remove()); state.markers.clear(); const L = window.L; [...state.geography, ...state.places].forEach((r)=>{ if(!Number.isFinite(r.lat)||!Number.isFinite(r.lon)) return; const marker = L.circleMarker([r.lat,r.lon], { radius:r.kind==="places"?8:6, color:"#fff", weight:1, fillColor:r.kind==="places"?"#ffc86b":"#61d1ff", fillOpacity:0.95 }).addTo(state.map); marker.bindPopup(`<b>${r.name || r.city || "Punto"}</b><br>${r.label || ""}`); state.markers.set(r.id, marker); }); }

function setWindow(mode){ state.activeWindow = mode; document.querySelectorAll("#view-world .world-tab").forEach((b)=>b.classList.toggle("active", b.dataset.window===mode)); document.querySelectorAll("#view-world [data-window-panel]").forEach((p)=>p.classList.toggle("active", p.dataset.windowPanel===mode)); invalidateLeafletMap(state.map, 60); }

function renderGeoList(){ const list = state.geography; const countries = [...new Set(list.map((g)=>g.countryCode).filter(Boolean))]; $id("world-country-filter").innerHTML = `<option value="all">Todos los países</option>${countries.map((cc)=>`<option value="${cc}">${flag(cc)} ${getCountryEnglishName(cc)||cc}</option>`).join("")}`; const filter = $id("world-country-filter").value || "all"; const rows = list.filter((g)=>filter==="all" || g.countryCode===filter); const by = new Map(); rows.forEach((r)=>{ const k = r.countryCode || "??"; if(!by.has(k)) by.set(k, []); by.get(k).push(r); }); $id("world-country-list").innerHTML = [...by.entries()].map(([cc, items])=>{ const avg = items.reduce((a,b)=>a+(b.rating||0),0)/Math.max(items.filter((x)=>x.rating!==null).length,1); return `<details open><summary>${flag(cc)} ${getCountryEnglishName(cc)||cc}<div>${stars10(avg)} ${avg.toFixed(1)}/10</div></summary>${items.map((r)=>`<button class="world-geo-item" data-geo-center="${r.id}">${r.name || r.city}<small>${r.label || ""}</small></button>`).join("")}</details>`; }).join("") || "<div>Sin lugares geográficos.</div>"; }
function renderLocals(){ const mode = $id("world-locals-group")?.value || "country"; const groups = {}; state.places.forEach((p)=>{ const k = mode === "city" ? (p.city || "Sin ciudad") : (p.countryCode || "??"); (groups[k] ||= []).push(p); }); $id("world-locals-list").innerHTML = Object.entries(groups).map(([k,rows])=>{ const avg = rows.reduce((a,b)=>a+(b.rating||0),0)/Math.max(rows.length,1); const cc = mode === "country" ? k : rows[0]?.countryCode || ""; const title = mode === "country" ? `${flag(cc)} ${rows[0]?.country || getCountryEnglishName(cc) || cc}` : k; return `<details open><summary>${title}<div>${stars10(avg)}<br>${avg.toFixed(1)} · ${rows.length} local</div></summary>${rows.map((r)=>`<div class="world-local-row">🛍 ${r.name} — ${r.city || ""}</div>`).join("")}</details>`; }).join("") || "<div>Sin locales.</div>"; }
function renderStats(){ $id("world-countries").textContent = String(new Set(state.geography.map((x)=>x.countryCode).filter(Boolean)).size); $id("world-geo-count").textContent = String(state.geography.length); $id("world-rated-locals").textContent = String(state.places.length); }
function renderAll(){ renderStats(); renderMap(); renderGeoList(); renderLocals(); }

async function persistWorld(){ if(!state.rootRef) return; await set(state.rootRef, { geography:Object.fromEntries(state.geography.map((r)=>[r.id,r])), places:Object.fromEntries(state.places.map((r)=>[r.id,r])), updatedAt:Date.now() }); }
async function removeItem(kind,idv){ const p=ref(db, `${state.rootRef.toString().replace(/https:\/\/[^/]+\//,'')}/${kind}/${idv}`); await remove(p); }

async function searchGeo(q){ const u = new URL("https://nominatim.openstreetmap.org/search"); u.searchParams.set("q", q); u.searchParams.set("format", "jsonv2"); u.searchParams.set("addressdetails", "1"); u.searchParams.set("limit", "8"); const rows = await (await fetch(u)).json(); state.geoResults = (Array.isArray(rows) ? rows : []).map((r) => normalizeLocationAddress(r)).filter((r) => Number.isFinite(r.lat) && Number.isFinite(r.lon)); renderGeoResults(); }
async function searchPlace(q){ const c=state.userCenter; const radius=Number($id("world-place-radius").value||1000); const dLat=radius/111320, dLng=radius/(111320*Math.cos((c.lat*Math.PI)/180)); const u=new URL("https://nominatim.openstreetmap.org/search"); u.searchParams.set("q",q); u.searchParams.set("format","jsonv2"); u.searchParams.set("addressdetails","1"); u.searchParams.set("limit","24"); u.searchParams.set("bounded","1"); u.searchParams.set("viewbox",`${c.lon-dLng},${c.lat+dLat},${c.lon+dLng},${c.lat-dLat}`); const rows=await (await fetch(u)).json(); state.placeResults=(Array.isArray(rows)?rows:[]).map((raw)=>{ const r=normalizeLocationAddress(raw); return ({ ...r, distance:hav(c.lat,c.lon,Number(r.lat),Number(r.lon)) }); }).filter((r)=>r.distance<=radius).sort((a,b)=>a.distance-b.distance); renderPlaceResults(); }

function pickGeo(i){ const row = state.geoResults[i]; if(!row) return; const normalizedCountry = normalizeCountryFromAddress(row.address); state.selectedGeo = normalize({ id:`geo_${i}`, name:row.name, label:row.label, city:row.city || row.municipality, region:row.region, country:normalizedCountry.country, countryCode:normalizedCountry.countryCode, postalCode:row.postalCode, lat:row.lat, lon:row.lon, note:$id("world-geo-note").value, rating:state.rating }, "geography"); renderGeoResults(); }
function pickPlace(i){ const row = state.placeResults[i]; if(!row) return; const normalizedCountry = normalizeCountryFromAddress(row.address); state.selectedPlace = normalize({ id:`place_${i}`, name:row.name, label:row.label, city:row.city || row.municipality, country:normalizedCountry.country, countryCode:normalizedCountry.countryCode, category:$id("world-place-q").value, lat:row.lat, lon:row.lon, rating:state.rating, note:$id("world-place-note").value }, "places"); renderPlaceResults(); }

function bindUI(){
  const root=$id("view-world");
  root.addEventListener("click", async (e)=>{ const t=e.target.closest("button,label"); if(!t) return; if(t.matches(".world-tab")) return setWindow(t.dataset.window); if(t.id==="world-open-add") { $id("world-add-toggle").checked=true; setAddMode("geo"); resetWorldAddModalState(); }
    if(t.id==="world-add-mode-geo") setAddMode("geo"); if(t.id==="world-add-mode-place") setAddMode("place");
    if(t.dataset.geoPick) pickGeo(Number(t.dataset.geoPick));
    if(t.dataset.placePick) pickPlace(Number(t.dataset.placePick));
    if(t.dataset.placeCenter){ const r=state.placeResults[Number(t.dataset.placeCenter)]; if(r && state.miniMap){ state.miniMap.setView([r.lat,r.lon],17); } }
    if(t.dataset.geoCenter){ const m=state.markers.get(t.dataset.geoCenter); if(m){ state.map.panTo(m.getLatLng()); m.openPopup(); } }
    if(t.dataset.worldDelete){ const [kind,idv]=t.dataset.worldDelete.split(":"); await removeItem(kind,idv); }
  });
  $id("world-country-filter").addEventListener("change", renderGeoList);
  $id("world-locals-group").addEventListener("change", renderLocals);
  $id("world-geo-q").addEventListener("input", (e)=> e.target.value.trim().length>1 ? searchGeo(e.target.value.trim()) : ($id("world-geo-results").innerHTML = ""));
  $id("world-place-q").addEventListener("input", (e)=> e.target.value.trim().length>1 ? searchPlace(e.target.value.trim()) : ($id("world-place-results").innerHTML = ""));
  $id("world-place-radius").addEventListener("change", ()=> $id("world-place-q").dispatchEvent(new Event("input")));
  $id("world-geo-save").addEventListener("click", async ()=>{ if(!state.selectedGeo) return; state.selectedGeo.note = $id("world-geo-note").value.trim(); state.geography.push(state.selectedGeo); await persistWorld(); closeAddModal(); resetWorldAddModalState(); showToast("Lugar guardado"); });
  $id("world-place-save").addEventListener("click", async ()=>{ if(!state.selectedPlace) return; state.selectedPlace.rating = state.rating; state.selectedPlace.note = $id("world-place-note").value.trim(); state.places.push(state.selectedPlace); await persistWorld(); closeAddModal(); resetWorldAddModalState(); showToast("Lugar guardado"); });
  $id("world-add-toggle").addEventListener("change", ()=>{ if($id("world-add-toggle").checked) initMiniMap(); else resetWorldAddModalState(); });

  const rating = $id("world-rating-stars"); rating.addEventListener("pointerdown",(e)=>{ const move=(ev)=>{ state.rating=ratingFromPointer(rating, ev.clientX); renderRating(); }; move(e); window.addEventListener("pointermove", move); const up=()=>{ window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; window.addEventListener("pointerup", up); });
}

function initMiniMap(){ if(!window.L) return; const host=$id("world-mini-map"); if(!host) return; if(!state.miniMap) state.miniMap=createLeafletMap(host, { center:[state.userCenter.lat,state.userCenter.lon], zoom:15 }); state.miniMap.setView([state.userCenter.lat,state.userCenter.lon],15); renderPlaceResults(); }
async function getCurrentPositionSafe(){ if (!(window.isSecureContext && navigator.geolocation)) return null; return new Promise((resolve)=>navigator.geolocation.getCurrentPosition((pos)=>resolve({ lat:Number(pos.coords.latitude), lon:Number(pos.coords.longitude) }), ()=>resolve(null), { enableHighAccuracy:true, maximumAge:60000, timeout:12000 })); }

export async function init(){ if(state.initialized) return; state.initialized=true; await ensureLeaflet(); bindUI(); renderRating(); const p=await getCurrentPositionSafe(); if(p) state.userCenter=p; const uid=getCurrentUserDataRootKey() || auth.currentUser?.uid; if(!uid) return; state.rootRef=ref(db, WORLD_PATH(uid)); state.unsub=trackedOnValue(state.rootRef, (snap)=>{ const data=snap.val()||{}; state.geography=Object.values(data.geography||{}).map((x)=>normalize(x,"geography")); state.places=Object.values(data.places||{}).map((x)=>normalize(x,"places")); renderAll(); }, { key:"world-root", path:WORLD_PATH(uid), module:"world", mode:"onValue", reason:"world-sync", viewId:"view-world" }, onValue); }
export function destroy(){ if(state.unsub) state.unsub(); state.unsub=null; if(state.map){ destroyLeafletMap($id("world-map")); state.map=null; } if(state.miniMap){ destroyLeafletMap($id("world-mini-map")); state.miniMap=null; } state.initialized=false; }
export async function onShow(){ if(!state.initialized) await init(); setWindow(state.activeWindow); invalidateLeafletMap(state.map,70); }
export async function onHide(){ destroy(); }
export function getListenerCount(){ return state.unsub?1:0; }
