import { auth, db, firebasePaths, getCurrentUserDataRootKey } from "../../shared/firebase/index.js";
import { ref, get, onValue, update } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-database.js";
import { createLeafletMap, DEFAULT_MAP_CENTER_SPAIN, DEFAULT_MAP_ZOOM_SPAIN, destroyLeafletMap, ensureLeaflet, invalidateLeafletMap, MAX_AUTO_ZOOM, setLeafletViewForPoints } from "../../shared/vendors/leaflet.js";
import { trackedOnValue } from "../../shared/firebase/read-debug.js";
import { getCountryEnglishName } from "./countries.js";

const WORLD_PATH = (uid) => firebasePaths.world(uid);
const LS_VISITS = "world_visits_v1";
const LS_WATCH = "world_watchlist_v1";
const $id = (id) => document.getElementById(id);
const iso2 = (v) => String(v || "").trim().toUpperCase();
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[m]));
const todayKey = () => new Date().toISOString().slice(0, 10);
const parseJson = (k, f) => { try { return JSON.parse(localStorage.getItem(k) || "") ?? f; } catch { return f; } };
const saveJson = (k, v) => localStorage.setItem(k, JSON.stringify(v));

const state = { initialized: false, abortController: null, firebaseUnsub: null, firebaseRef: null, visits: [], watch: {}, customPins: [], areaVisits: [], timelineEntries: [], selected: null, rating: 0, mainMap: null, miniMap: null, miniMarker: null, searchMarkers: [] };

const normalizeRecord = (v = {}) => ({ id: String(v.id || `${Date.now()}_${Math.random().toString(16).slice(2)}`), ts: Number(v.ts) || Date.now(), status: v.status || "visited", kind: v.kind || "place", countryCode: iso2(v.countryCode || v.country || v.country_code), subdivision: String(v.subdivision || "").trim(), city: String(v.city || "").trim(), placeName: String(v.placeName || v.name || "").trim(), lat: Number.isFinite(Number(v.lat)) ? Number(v.lat) : null, lon: Number.isFinite(Number(v.lon)) ? Number(v.lon) : null, note: String(v.note || ""), rating: Number.isFinite(Number(v.rating)) ? Number(v.rating) : null, folder: String(v.folder || ""), visitDate: String(v.visitDate || todayKey()), origin: String(v.origin || "manual") });

function detectCategory(name = "") { const n = name.toLowerCase(); if (n.includes("burger king")) return "Burger King"; if (n.includes("mcdonald")) return "McDonald's"; if (n.includes("kfc")) return "KFC"; if (n.includes("farmacia") || n.includes("pharmacy")) return "Farmacias"; if (n.includes("baño") || n.includes("wc") || n.includes("toilet")) return "Baños"; if (n.includes("supermercado")) return "Supermercados"; if (n.includes("mall") || n.includes("centro comercial")) return "Centros comerciales"; if (n.includes("hotel")) return "Hoteles"; if (n.includes("caf")) return "Cafeterías"; if (n.includes("restaurante")) return "Restaurantes"; return "Otros"; }

async function geocodeReverse(lat, lon) { const u = new URL("https://nominatim.openstreetmap.org/reverse"); u.searchParams.set("format", "json"); u.searchParams.set("lat", String(lat)); u.searchParams.set("lon", String(lon)); u.searchParams.set("zoom", "16"); u.searchParams.set("addressdetails", "1"); const r = await fetch(u.toString()); const d = await r.json(); const a = d.address || {}; return { countryCode: iso2(a.country_code), country: a.country || "", subdivision: a.state || a.region || a.county || "", city: a.city || a.town || a.village || a.municipality || a.suburb || "", placeName: a.city || a.town || a.village || a.municipality || a.suburb || a.county || "" }; }
async function searchPlaces(q, lat, lon) { console.debug("[world:place-search:start]", { q }); const u = new URL("https://nominatim.openstreetmap.org/search"); u.searchParams.set("q", q); u.searchParams.set("format", "json"); u.searchParams.set("addressdetails", "1"); u.searchParams.set("limit", "10"); if (Number.isFinite(lat) && Number.isFinite(lon)) { u.searchParams.set("viewbox", `${lon - 0.3},${lat + 0.3},${lon + 0.3},${lat - 0.3}`); u.searchParams.set("bounded", "1"); } const r = await fetch(u.toString()); const d = await r.json(); console.debug("[world:place-search:results]", { count: d.length }); return d; }

function renderRatings() { const host = $id("world-rating"); if (!host) return; host.innerHTML = Array.from({ length: 11 }, (_, i) => `<button type="button" data-rate="${i}" class="${state.rating === i ? "active" : ""}">${i}</button>`).join(""); host.querySelectorAll("button").forEach((b) => b.onclick = () => { state.rating = Number(b.dataset.rate); renderRatings(); }); }

async function renderMap() { const records = [...state.visits, ...state.customPins, ...state.areaVisits].filter((r) => Number.isFinite(r.lat) && Number.isFinite(r.lon)); if (!state.mainMap) state.mainMap = createLeafletMap($id("world-map"), { center: DEFAULT_MAP_CENTER_SPAIN, zoom: DEFAULT_MAP_ZOOM_SPAIN }); const map = state.mainMap; if (!map) return; map.eachLayer((l) => { if (l?.options?.pane === "markerPane") map.removeLayer(l); }); const L = window.L; const points = []; records.forEach((r) => { const color = r.origin === "current_location" ? "#7ff0a1" : (r.rating != null ? "#ffc857" : "#4fd0ff"); const marker = L.circleMarker([r.lat, r.lon], { radius: 4, color: "#fff", weight: 1, fillColor: color, fillOpacity: .9 }).addTo(map); marker.on("click", () => map.setView([r.lat, r.lon], 12)); points.push({ lat: r.lat, lng: r.lon }); }); setLeafletViewForPoints(map, points, { defaultCenter: DEFAULT_MAP_CENTER_SPAIN, defaultZoom: DEFAULT_MAP_ZOOM_SPAIN, maxAutoZoom: MAX_AUTO_ZOOM, singlePointZoom: 10 }); invalidateLeafletMap(map, 50); console.debug("[world:markers:render]", { count: points.length }); }

function renderLists() { const all = [...state.visits, ...state.customPins, ...state.areaVisits]; const countries = new Map(); all.forEach((r) => { if (!r.countryCode) return; if (!countries.has(r.countryCode)) countries.set(r.countryCode, []); countries.get(r.countryCode).push(r); }); const countryHost = $id("world-country-list"); countryHost.innerHTML = [...countries.entries()].map(([code, rows]) => `<details class="world-country-row"><summary>${esc(getCountryEnglishName(code) || code)} (${rows.length})</summary>${rows.map((r) => `<div class="world-item"><div><div class="name">${esc(r.city || r.placeName || "Sin nombre")}</div><div class="meta">${esc([r.subdivision, getCountryEnglishName(code) || code].filter(Boolean).join(", "))}</div></div><div class="actions"><button class="btn" data-center="${r.id}">Centrar</button></div></div>`).join("")}</details>`).join("");
  const rated = all.filter((r) => r.rating != null);
  const groups = new Map(); rated.forEach((r) => { const key = r.folder || detectCategory(r.placeName); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(r); });
  const localsHost = $id("world-locals-list");
  localsHost.innerHTML = [...groups.entries()].map(([k, rows]) => `<details class="world-country-row"><summary>${esc(k)} (${rows.length})</summary>${rows.map((r) => `<div class="world-item"><div><div class="name">${esc(r.placeName)}</div><div class="meta">${esc([r.city, getCountryEnglishName(r.countryCode) || r.countryCode].filter(Boolean).join(", "))} · ${r.rating}/10</div><div class="meta">${esc(r.note || "")}</div></div><div class="actions"><button class="btn" data-center="${r.id}">Centrar</button><button class="btn" data-del="${r.id}">Borrar</button></div></div>`).join("")}</details>`).join("") || '<div class="geo-empty">Sin locales valorados.</div>';
  $id("world-country-count").textContent = String(countries.size); $id("world-locals-count").textContent = String(rated.length); $id("world-countries").textContent = String(countries.size); $id("world-places").textContent = String(all.length); $id("world-rated-locals").textContent = String(rated.length);
  console.debug("[world:list:render]", { countries: countries.size, rated: rated.length });
}

function persist() { saveJson(LS_VISITS, state.visits); saveJson(LS_WATCH, state.watch); if (state.firebaseRef) update(state.firebaseRef, { visits: state.visits, watch: state.watch, customPins: state.customPins, areaVisits: state.areaVisits, timelineEntries: state.timelineEntries, updatedAt: Date.now() }); }

async function renderAll() { await renderMap(); renderLists(); }

export async function init() { if (state.initialized) return; state.initialized = true; state.abortController = new AbortController(); console.debug("[world:init]"); state.visits = parseJson(LS_VISITS, []).map(normalizeRecord); state.watch = parseJson(LS_WATCH, {});
  const uid = getCurrentUserDataRootKey() || auth.currentUser?.uid; if (uid) { state.firebaseRef = ref(db, WORLD_PATH(uid)); state.firebaseUnsub = trackedOnValue(state.firebaseRef, (s) => { const v = s.val() || {}; state.visits = (v.visits || state.visits).map(normalizeRecord); state.customPins = (v.customPins || []).map(normalizeRecord); state.areaVisits = (v.areaVisits || []).map(normalizeRecord); state.timelineEntries = (v.timelineEntries || []).map(normalizeRecord); renderAll(); }, { key: "world-root", path: WORLD_PATH(uid), module: "world", mode: "onValue", reason: "world-live-sync", viewId: "view-world" }, onValue); }
  await ensureLeaflet(); renderRatings();
  $id("world-mark-current")?.addEventListener("click", () => navigator.geolocation?.getCurrentPosition(async (pos) => { const geo = await geocodeReverse(pos.coords.latitude, pos.coords.longitude); const rec = normalizeRecord({ ...geo, lat: pos.coords.latitude, lon: pos.coords.longitude, placeName: [geo.city, geo.subdivision, geo.country].filter(Boolean).join(", "), origin: "current_location", status: "visited" }); state.visits.push(rec); persist(); console.debug("[world:current-location:save]", rec); renderAll(); }));
  $id("world-place-q")?.addEventListener("input", async (e) => { const q = e.target.value.trim(); if (q.length < 2) return; const cur = state.selected; const results = await searchPlaces(q, cur?.lat, cur?.lon); const host = $id("world-place-results"); host.innerHTML = results.map((r, i) => `<div class="world-item"><div><div class="name">${esc((r.display_name || '').split(',')[0])}</div><div class="meta">${esc(r.display_name || '')}</div></div><button class="btn" data-pick="${i}">Elegir</button></div>`).join(''); host.querySelectorAll('[data-pick]').forEach((b) => b.onclick = async () => { const r = results[Number(b.dataset.pick)]; state.selected = r; console.debug('[world:place:selected]', { name: r.display_name }); }); });
  $id("world-place-save")?.addEventListener("click", async () => { if (!state.selected) return; const r = state.selected; const a = r.address || {}; const rec = normalizeRecord({ placeName: (r.display_name || '').split(',')[0], city: a.city || a.town || a.village || a.municipality || a.suburb || '', subdivision: a.state || a.county || '', countryCode: iso2(a.country_code), lat: Number(r.lat), lon: Number(r.lon), rating: state.rating, note: $id('world-note').value.trim(), folder: detectCategory((r.display_name || '').split(',')[0]), status: 'visited', origin: 'search' }); state.visits.push(rec); persist(); console.debug('[world:place:save]', rec); $id('world-add-toggle').checked = false; renderAll(); });
  document.getElementById('view-world')?.addEventListener('click', (e) => { const c = e.target.closest('[data-center]'); if (c) { const id = c.dataset.center; const rec = [...state.visits, ...state.customPins, ...state.areaVisits].find((x) => x.id === id); if (rec && state.mainMap) state.mainMap.setView([rec.lat, rec.lon], 12); } const d = e.target.closest('[data-del]'); if (d) { const id = d.dataset.del; state.visits = state.visits.filter((x) => x.id !== id); persist(); renderAll(); } });
  await renderAll(); }

export function destroy() { if (state.mainMap) { destroyLeafletMap($id('world-map')); state.mainMap = null; } state.abortController?.abort(); if (state.firebaseUnsub) state.firebaseUnsub(); state.initialized = false; }
export function getListenerCount() { return (state.abortController ? 1 : 0) + (state.firebaseUnsub ? 1 : 0); }
export async function onShow() { if (!state.initialized) await init(); }
export async function onHide() { destroy(); }
