import { auth, db, firebasePaths, getCurrentUserDataRootKey } from "../../shared/firebase/index.js";
import { ref, onValue, update } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-database.js";
import { createLeafletMap, DEFAULT_MAP_CENTER_SPAIN, DEFAULT_MAP_ZOOM_SPAIN, destroyLeafletMap, ensureLeaflet, invalidateLeafletMap, MAX_AUTO_ZOOM, setLeafletViewForPoints } from "../../shared/vendors/leaflet.js";
import { trackedOnValue } from "../../shared/firebase/read-debug.js";
import { getCountryEnglishName } from "./countries.js";

const WORLD_PATH = (uid) => firebasePaths.world(uid);
const $id = (id) => document.getElementById(id);
const iso2 = (v) => String(v || "").trim().toUpperCase();
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[m]));
const todayKey = () => new Date().toISOString().slice(0, 10);

const state = { initialized: false, firebaseUnsub: null, firebaseRef: null, visits: [], customPins: [], areaVisits: [], selected: null, rating: 0, mainMap: null, markerLayer: null, scope: { countryCode: "", city: "" }, filters: { category: "", ratingMin: 0 } };

const normalizeRecord = (v = {}) => ({ id: String(v.id || `${Date.now()}_${Math.random().toString(16).slice(2)}`), ts: Number(v.ts) || Date.now(), status: v.status || "visited", kind: v.kind || "place", countryCode: iso2(v.countryCode || v.country || v.country_code), subdivision: String(v.subdivision || "").trim(), city: String(v.city || "").trim(), placeName: String(v.placeName || v.name || "").trim(), lat: Number.isFinite(Number(v.lat)) ? Number(v.lat) : null, lon: Number.isFinite(Number(v.lon)) ? Number(v.lon) : null, note: String(v.note || ""), rating: Number.isFinite(Number(v.rating)) ? Number(v.rating) : null, folder: String(v.folder || v.category || ""), visitDate: String(v.visitDate || todayKey()), origin: String(v.origin || "manual") });

function detectCategory(name = "") { const n = name.toLowerCase(); console.debug("[world:category:detect]", { name }); if (n.includes("burger king") || n.includes("mcdonald") || n.includes("kfc")) return "Comida rápida"; if (n.includes("farmacia") || n.includes("pharmacy")) return "Farmacias"; if (n.includes("baño") || n.includes("wc") || n.includes("toilet")) return "Baños"; if (n.includes("supermercado")) return "Supermercados"; if (n.includes("mall") || n.includes("centro comercial")) return "Centros comerciales"; if (n.includes("hotel")) return "Hoteles"; if (n.includes("caf") || n.includes("bar") || n.includes("restaurante")) return "Restauración"; if (n.includes("museo") || n.includes("parque") || n.includes("monumento")) return "Turismo"; return "Otros"; }
async function geocodeReverse(lat, lon) { const u = new URL("https://nominatim.openstreetmap.org/reverse"); u.searchParams.set("format", "json"); u.searchParams.set("lat", String(lat)); u.searchParams.set("lon", String(lon)); u.searchParams.set("addressdetails", "1"); const r = await fetch(u.toString()); const d = await r.json(); const a = d.address || {}; return { countryCode: iso2(a.country_code), country: a.country || "", subdivision: a.state || a.region || "", city: a.city || a.town || a.village || a.municipality || "" }; }
async function searchPlaces(q) { const u = new URL("https://nominatim.openstreetmap.org/search"); u.searchParams.set("q", q); u.searchParams.set("format", "json"); u.searchParams.set("addressdetails", "1"); u.searchParams.set("limit", "10"); const r = await fetch(u.toString()); return r.json(); }

function getAll() { return [...state.visits, ...state.customPins, ...state.areaVisits].map(normalizeRecord); }
function getScopedRecords() { return getAll().filter((r) => (!state.scope.countryCode || r.countryCode === state.scope.countryCode) && (!state.scope.city || r.city.toLowerCase() === state.scope.city.toLowerCase()) && (!state.filters.category || (r.folder || detectCategory(r.placeName)) === state.filters.category) && (!state.filters.ratingMin || (r.rating ?? -1) >= state.filters.ratingMin)); }
function persist() { if (state.firebaseRef) update(state.firebaseRef, { visits: state.visits, customPins: state.customPins, areaVisits: state.areaVisits, updatedAt: Date.now() }); }

function renderRatings() { const host = $id("world-rating"); host.innerHTML = Array.from({ length: 21 }, (_, i) => i / 2).map((v) => `<button type=button data-rate="${v}" class="${state.rating === v ? "active" : ""}">${v}</button>`).join(""); host.querySelectorAll("button").forEach((b) => b.onclick = () => { state.rating = Number(b.dataset.rate); renderRatings(); }); }
function renderScope() { const host = $id("world-scope"); const p = []; if (state.scope.countryCode) p.push(getCountryEnglishName(state.scope.countryCode) || state.scope.countryCode); if (state.scope.city) p.push(state.scope.city); host.innerHTML = `<button class="btn" data-nav="root">🌍 Mundo</button>${state.scope.countryCode ? `<button class="btn" data-nav="country">${esc(getCountryEnglishName(state.scope.countryCode) || state.scope.countryCode)}</button>` : ""}${state.scope.city ? `<button class="btn" data-nav="city">${esc(state.scope.city)}</button>` : ""}`; }

async function renderMap() { const records = getScopedRecords().filter((r) => Number.isFinite(r.lat) && Number.isFinite(r.lon)); if (!state.mainMap) state.mainMap = createLeafletMap($id("world-map"), { center: DEFAULT_MAP_CENTER_SPAIN, zoom: DEFAULT_MAP_ZOOM_SPAIN }); const map = state.mainMap; const L = window.L; if (state.markerLayer) map.removeLayer(state.markerLayer); const markers = records.map((r) => { const color = r.origin === "current_location" ? "#7ff0a1" : (r.city && !r.placeName ? "#6f6bff" : "#4fd0ff"); return L.circleMarker([r.lat, r.lon], { radius: 3, color: "#fff", weight: 0.7, fillColor: color, fillOpacity: .92 }).bindTooltip(`${esc(r.placeName || r.city || "Punto")} · ${r.rating ?? "-"}/10`); }); state.markerLayer = L.markerClusterGroup ? L.markerClusterGroup({ maxClusterRadius: 25 }) : L.layerGroup(); markers.forEach((m) => state.markerLayer.addLayer(m)); map.addLayer(state.markerLayer); setLeafletViewForPoints(map, records.map((r) => ({ lat: r.lat, lng: r.lon })), { defaultCenter: DEFAULT_MAP_CENTER_SPAIN, defaultZoom: DEFAULT_MAP_ZOOM_SPAIN, maxAutoZoom: MAX_AUTO_ZOOM, singlePointZoom: 11 }); invalidateLeafletMap(map, 50); console.debug("[world:map:markers:render]", { count: records.length }); }

function renderLists() { const records = getScopedRecords(); const countryHost = $id("world-country-list"); const localsHost = $id("world-locals-list");
  if (!state.scope.countryCode) {
    const countries = new Map(); getAll().forEach((r) => { if (!r.countryCode) return; if (!countries.has(r.countryCode)) countries.set(r.countryCode, []); countries.get(r.countryCode).push(r); });
    countryHost.innerHTML = [...countries.entries()].map(([code, rows]) => `<div class="world-item"><div><div class="name">${esc(getCountryEnglishName(code) || code)}</div><div class="meta">${rows.length} puntos · ${new Set(rows.map((r) => r.city).filter(Boolean)).size} ciudades</div></div><div class="actions"><button class="btn" data-open-country="${code}">Abrir</button></div></div>`).join("");
    $id("world-list-title").textContent = "Países visitados";
  } else if (!state.scope.city) {
    const cities = new Map(); records.forEach((r) => { const c = r.city || "Sin ciudad"; if (!cities.has(c)) cities.set(c, []); cities.get(c).push(r); });
    countryHost.innerHTML = [...cities.entries()].map(([city, rows]) => `<div class="world-item"><div><div class="name">${esc(city)}</div><div class="meta">${rows.length} lugares</div></div><div class="actions"><button class="btn" data-open-city="${esc(city)}">Abrir</button></div></div>`).join("");
    $id("world-list-title").textContent = "Ciudades/Pueblos";
  } else {
    countryHost.innerHTML = records.map((r) => `<div class="world-item"><div><div class="name">${esc(r.placeName || "Lugar")}</div><div class="meta">${esc(r.folder || detectCategory(r.placeName))} · ${r.rating ?? "-"}/10</div></div><div class="actions"><button class="btn" data-center="${r.id}">Mapa</button><button class="btn" data-edit="${r.id}">Editar</button><button class="btn" data-del="${r.id}">Borrar</button></div></div>`).join("") || '<div class="geo-empty">Sin lugares.</div>';
    $id("world-list-title").textContent = "Lugares guardados";
  }
  const rated = getAll().filter((r) => r.rating != null).sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0)).slice(0, 20);
  localsHost.innerHTML = rated.map((r) => `<div class="world-item"><div><div class="name">${esc(r.placeName || r.city || "Punto")}</div><div class="meta">${esc(r.city)} · ${esc(r.folder || detectCategory(r.placeName))} · ${r.rating}/10</div></div><div class="actions"><button class="btn" data-center="${r.id}">Centrar</button></div></div>`).join("") || '<div class="geo-empty">Sin valoraciones.</div>';
  const categories = new Set(getAll().map((r) => r.folder || detectCategory(r.placeName)));
  $id("world-countries").textContent = String(new Set(getAll().map((r) => r.countryCode).filter(Boolean)).size); $id("world-places").textContent = String(getAll().length); $id("world-rated-locals").textContent = String(rated.length); $id("world-country-count").textContent = String(records.length); $id("world-locals-count").textContent = String(rated.length); $id("world-categories").textContent = String(categories.size);
  const catSel = $id("world-filter-category"); const selected = catSel.value; catSel.innerHTML = `<option value="">Todas categorías</option>${[...categories].sort().map((c) => `<option ${selected === c ? "selected" : ""} value="${esc(c)}">${esc(c)}</option>`).join("")}`;
}

async function renderAll() { renderScope(); await renderMap(); renderLists(); }

export async function init() { if (state.initialized) return; state.initialized = true; console.debug("[world:init]");
  const uid = getCurrentUserDataRootKey() || auth.currentUser?.uid; if (uid) { state.firebaseRef = ref(db, WORLD_PATH(uid)); state.firebaseUnsub = trackedOnValue(state.firebaseRef, (s) => { const v = s.val() || {}; state.visits = (v.visits || []).map(normalizeRecord); state.customPins = (v.customPins || []).map(normalizeRecord); state.areaVisits = (v.areaVisits || []).map(normalizeRecord); renderAll(); }, { key: "world-root", path: WORLD_PATH(uid), module: "world", mode: "onValue", reason: "world-live-sync", viewId: "view-world" }, onValue); }
  await ensureLeaflet(); renderRatings();
  $id("world-mark-current")?.addEventListener("click", () => navigator.geolocation?.getCurrentPosition(async (pos) => { const geo = await geocodeReverse(pos.coords.latitude, pos.coords.longitude); const rec = normalizeRecord({ ...geo, lat: pos.coords.latitude, lon: pos.coords.longitude, placeName: geo.city || "Ubicación actual", folder: detectCategory(geo.city), status: "visited", origin: "current_location" }); state.visits.push(rec); persist(); console.debug("[world:location:current:save]", rec); renderAll(); }));
  $id("world-place-q")?.addEventListener("input", async (e) => { const q = e.target.value.trim(); if (q.length < 2) return; const results = await searchPlaces(q); const host = $id("world-place-results"); host.innerHTML = results.map((r, i) => `<div class="world-item"><div><div class="name">${esc((r.display_name || '').split(',')[0])}</div><div class="meta">${esc(r.display_name || '')}</div></div><button class="btn" data-pick="${i}">Elegir</button></div>`).join(''); host.querySelectorAll('[data-pick]').forEach((b) => b.onclick = () => { const r = results[Number(b.dataset.pick)]; state.selected = r; const city = r.address?.city || r.address?.town || r.address?.village || ""; $id("world-place-city").value = city; $id("world-place-category").value = detectCategory((r.display_name || '').split(',')[0]); }); });
  $id("world-place-save")?.addEventListener("click", () => { if (!state.selected) return; const r = state.selected; const a = r.address || {}; const name = (r.display_name || '').split(',')[0]; const rec = normalizeRecord({ placeName: name, city: $id("world-place-city").value.trim() || a.city || a.town || '', subdivision: a.state || a.county || '', countryCode: iso2(a.country_code), lat: Number(r.lat), lon: Number(r.lon), rating: state.rating, note: $id('world-note').value.trim(), folder: $id('world-place-category').value.trim() || detectCategory(name), status: 'visited', origin: 'search' }); state.visits.push(rec); persist(); console.debug('[world:place:save]', rec); renderAll(); });
  document.getElementById('view-world')?.addEventListener('click', (e) => { const openCountry = e.target.closest('[data-open-country]'); if (openCountry) { state.scope.countryCode = openCountry.dataset.openCountry; state.scope.city = ""; console.debug("[world:country:open]", { country: state.scope.countryCode }); renderAll(); } const openCity = e.target.closest('[data-open-city]'); if (openCity) { state.scope.city = openCity.dataset.openCity; console.debug("[world:city:open]", { city: state.scope.city }); renderAll(); } const nav = e.target.closest('[data-nav]'); if (nav) { if (nav.dataset.nav === "root") state.scope = { countryCode: "", city: "" }; if (nav.dataset.nav === "country") state.scope.city = ""; renderAll(); } const c = e.target.closest('[data-center]'); if (c) { const rec = getAll().find((x) => x.id === c.dataset.center); if (rec && state.mainMap) state.mainMap.setView([rec.lat, rec.lon], 13); } const d = e.target.closest('[data-del]'); if (d) { state.visits = state.visits.filter((x) => x.id !== d.dataset.del); persist(); renderAll(); } const ed = e.target.closest('[data-edit]'); if (ed) { const rec = getAll().find((x) => x.id === ed.dataset.edit); if (!rec) return; const newRating = prompt("Valoración 0-10", String(rec.rating ?? 0)); if (newRating != null) rec.rating = Number(newRating); const newCat = prompt("Categoría", rec.folder || detectCategory(rec.placeName)); if (newCat != null) rec.folder = newCat; state.visits = state.visits.map((x) => x.id === rec.id ? rec : x); persist(); console.debug("[world:place:rate]", { id: rec.id, rating: rec.rating }); renderAll(); } });
  $id("world-filter-category")?.addEventListener("change", (e) => { state.filters.category = e.target.value; console.debug("[world:places:load]", state.filters); renderAll(); });
  $id("world-filter-rating")?.addEventListener("change", (e) => { state.filters.ratingMin = Number(e.target.value || 0); console.debug("[world:places:load]", state.filters); renderAll(); });
  await renderAll(); }

export function destroy() { if (state.mainMap) { destroyLeafletMap($id('world-map')); state.mainMap = null; } if (state.firebaseUnsub) state.firebaseUnsub(); state.initialized = false; }
export function getListenerCount() { return state.firebaseUnsub ? 1 : 0; }
export async function onShow() { if (!state.initialized) await init(); }
export async function onHide() { destroy(); }
