export const LEGACY_PATH = 'finance';
export const DEVICE_KEY = 'finance_deviceId';
export const HOME_PANEL_VIEW_KEY = 'bookshell_finance_home_panel_view';
export const RANGE_LABEL = { total: 'Total', month: 'Mes', week: 'Semana', year: 'Año' };
export const BTC_PRICE_CACHE_KEY = 'bookshell_finance_btc_eur_cache_v1';
export const BTC_PRICE_CACHE_TTL_MS = 20 * 60 * 1000;
export const AGG_MODES = ['day', 'week', 'month', 'year', 'total'];
export const FINANCE_DEBUG = false;

export const state = {
  deviceId: '',
  financePath: '',
  rangeMode: 'month',
  compareMode: 'month',
  activeView: 'home',
  homePanelView: localStorage.getItem(HOME_PANEL_VIEW_KEY) === 'calendar' ? 'calendar' : 'hero',
  accounts: [],
  legacyEntries: {},
  balance: { tx: {}, movements: {}, transactions: {}, categories: {}, budgets: {}, snapshots: {}, recurring: {}, aggregates: {}, defaultAccountId: '', lastSeenMonthKey: '' },
  goals: { goals: {} },
  modal: { type: null, accountId: null, goalId: null, budgetId: null, txType: '', monthOffset: 0, importRaw: '', importPreview: null, importError: '' },
  balanceFormState: {},
  toast: '',
  calendarMonthOffset: 0,
  calendarAccountId: 'total',
  calendarMode: 'day',
  balanceMonthOffset: 0,
  balanceFilterType: 'all',
  balanceFilterCategory: 'all',
  balanceAccountFilter: 'all',
  balanceShowAllTx: false,
  balanceTxDetailsOpen: false,
  balanceStatsMode: 'expense',
  balanceStatsRange: 'month',
  balanceStatsGroupBy: 'category',
  balanceStatsScope: 'personal',
  balanceStatsIncludeUnlined: false,
  balanceStatsActiveSegment: null,
  balanceStatsSelectedSliceKey: null,
  balanceStatsLegendExpanded: true,
  balanceFilterUnlinedOnly: false,
  balanceAggScope: 'my',
  balanceAmountAuto: true,
  lastMovementAccountId: localStorage.getItem('bookshell_finance_lastMovementAccountId') || '',
  unsubscribe: null,
  saveTimers: {},
  food: { loaded: false, loading: false, options: { typeOfMeal: {}, cuisine: {}, place: {} }, items: {}, itemsById: {}, nameToId: {} },
  foodCatalog: { loaded: false, loading: false, canonicals: {}, aliases: {}, ignored: {}, merges: {} },
  foodProductsView: { range: 'month', rangeValue: '', vendor: 'all', account: 'all', onlyWithItems: false, tab: 'top-eur', customStart: '', customEnd: '', productsQuery: '', scope: 'personal' },
  hydratedFromRemote: false,
  btcEurPrice: 0,
  btcPriceTs: 0,
  aggregateRebuildTimer: null,
  error: '',
  booted: false,
  firstInitDone: false,
  eventsAbortController: null,
  calendarFixedView: 'squares',
calendarMainView: 'fixed',
};
